run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - unused
    - ineffassign
    - typecheck

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: unused-parameter
        severity: warning
      - name: indent-error-flow
      - name: error-return
      - name: blank-imports
      - name: context-as-argument
      - name: empty-lines

issues:
  # Don’t block PRs due to long lints
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude vendor folders
  exclude-dirs:
    - vendor

  # Common false positives
  exclude:
    - "should have comment"   # disable old golint-style comment errors
